# These are stored in .bksconfig 
dataTypes:
  bool: Boolean
  num: Number
  int: Integer
  str: String
  curr: Currency
  date: Date
  shortcode: Shorthand code
  catcode: Category code
expenseFields:
  - slug: date
    title: Purchase date
    type: date
    required: true
  - slug: amount
    title: Whole purchase amount (inc GST)
    type: curr
    required: true
  - slug: gst
    title: Has GST
    type: bool
    default:  true
  - slug: deduction
    title: Is deduction
    type: bool
    default: true
  - slug: percentage
    title: Percentage deductible
    type: number
    default: 1 
  - slug: description
    title: Description
    type: str
    required: false
  - slug: shortcode
    title: Shorthand code
    type: shortcode
    required: false  
  - slug: catcode
    title: Category code
    type: catcode
    required: false